dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: channelape-github
    token:
      secure: EHyqb+NjwY29lysfyfyogVYjhnTU2BTx/oLvRjZ15tXcFx2jUj3cfY/97zQYjF8r9laqdBonlryrTAIdOyp4he3cdY4Xll3I14e+biT49bdhyMofSAFQbNuFpxpBNuVcg4sJBfmj5CB1qhcvTTq+oEKNpAjJV3QZfTVcvsE1dNgRWHWOq3mm7G97TGYOF58Rjm601KaBEqXNAMKO1fCp2D6lJ/VA9uGAlhkTWz+7SsdjuxE7FqHFBeIqNyoR8utuh6GVkWnJmaMPlFnZLwmuB3ojz2Y6h5PVINPCnz7ZeLbAldOp5QXJQIL5Rt+ZBhP8bGlZTEzYwp3O/77TkQhgvfkyHXoDMmkweCtKP+fj/NAlcQpa+iiFvalEOVz9CV+21WL3SRqqOZNEpEqaj3zPIlflsFpD79Wk4Zxa44QtmV6AOPVE5JsQfPq2cDhyv2KS4sU3cIjaZOKKXwMJKga7F+eGI/i/kCw9LJqlCNxLHJLI9/c7byn+rUHhu1DN3bz5TmR/K08M9JMGbVUGfpA1vAn0eW58H2qm/Ifi4oF5WaFVpXPvAA36BwOHl7wzSd8uQKyoXc6IQhxAn+awxAgibOImgsyavUN09rAO7+RKwQpqiLpfU68fLhaz+O5PMDe+727Bt6F5ILteL0xp2uyIY+Aau5FIAdTemRin4t4YUGM=
language: node_js
node_js:
  - 8.10.0
jdk:
  - oraclejdk8
install:
  - npm install
script:
  - npm test
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run e2e; fi
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/overwrite-sonar-project-version.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
cache:
  directories:
    - node_modules
    - "$HOME/.sonar/cache"
deploy:
  - provider: npm
    skip_cleanup: true
    email:
      - "$NPM_EMAIL"
    api_key:
      - "$NPM_TOKEN"
    tag: develop
    on:
      branch: develop
  - provider: npm
    skip_cleanup: true
    email:
      - "$NPM_EMAIL"
    api_key:
      - "$NPM_TOKEN"
    tag: latest
    on:
      branch: master
